export const GET_USER_START = "GET_USER_START";
export const GET_USER_COMPLETE = "GET_USER_COMPLETE";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const ADD_USER_START = "ADD_USER_START";
export const ADD_USER_COMPLETE = "ADD_USER_COMPLETE";
export const ADD_USER_ERROR = "ADD_USER_ERROR";

export const UPDATE_USER_START = "UPDATE_USER_START";
export const UPDATE_USER_COMPLETE = "UPDATE_USER_COMPLETE";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const DELETE_USER_START = "DELETE_USER_START";
export const DELETE_USER_COMPLETE = "DELETE_USER_COMPLETE";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";
